version: '3.8'

services:
  server:
    build: ./server
    ports:
      - '8000:8000'
    env_file: ./server/.env

  client:
    build: ./client
    ports:
      - '5173:80'
    depends_on:
      - server
